### ISSUE TITLE
TypeError: unhashable type: '_cbor2.CBORTag'

### ISSUE THREAD

**Issue by nielstron** [agronholm/cbor2#147]
The following code gives me a rather obscure error message. `TypeError: unhashable type: '_cbor2.CBORTag'`
```
import cbor2

cbor = bytes.fromhex("d8799f4469555344d8799fd8799f1b0dd612c92160462cffd8799fc24d0af6e24f990db06e7dd5a6a810ffd8799f1b008b36bf518dee53ff0100ffa2d8799f0000ffd8799f1b084494e2d23b2b7effd8799f0100ffd8799f1b008b36bf518dee53ffff")
res = cbor2.loads(cbor)
print(res)
```
However, using cbor.me, I am perfectly able to correctly load the cbor. I assume there is a bug in the implementation?

**Comment by nielstron** [comment]
Interesting enough, the pure command line usage throws no error:
`echo d8799f4469555344d8799fd8799f1b0dd612c92160462cffd8799fc24d0af6e24f990db06e7dd5a6a810ffd8799f1b008b36bf518dee53ff0100ffa2d8799f0000ffd8799f1b084494e2d23b2b7effd8799f0100ffd8799f1b008b36bf518dee53ffff | xxd -r -ps | python -m cbor2.tool --pretty`

**Comment by Sekenre** [comment]
Hi @nielstron Thanks for raising this one. At the moment, we're trying to keep functionality identical between the C library `_cbor2` and the pure python implementation. Since we don't have a `__hash__` method on the C object, we can't have one on the Python object.

However, a change I intend to make for the next major version update is to always use the pure python tag object. We would then be free to make it hashable.

It works in the command line because the default tag_handler in that module converts tags to their string equivalent (purely diagnostic, not reversible)

You can also work around this by adding a tag handler that can return a hashable object of your choosing.

**Comment by nielstron** [comment]
If that is the issue, I just pushed a version in #148 that adds an equivalent hash function to both the python version and the C version of the object.

**Comment by Sekenre** [comment]
Merged. That's been bugging me for ages and I had been putting off learning how to do it in Python's C API
