### ISSUE TITLE
requesting support for decoding multiple objects

### ISSUE THREAD

**Issue by toravir** [agronholm/cbor2#60]
When the logs are in cbor format, there are multiple objects - they are NOT in an array - just objects back to back to back. Example like:

```
{"price":100,"Desc":"Hundred Dollars","level":"info","time":"2019-09-23T11:25:50-07:00"}
{"price":1000,"Desc":"Thousand Dollars","level":"warn","time":"2019-09-23T11:25:50-07:00"}
{"price":1000,"Desc":"Without TS","level":"warn"}
```
load() and loads() just returns the first log line.

One such logger is github.com/rs/zerolog - the binary log format is a CBOR.

**Comment by waveform80** [comment]
I may be missing something here, but while `loads()` will only return the first log line (and it's all I'd *expect* it to return if called with the same input time and again), `load()` most certainly won't provided you don't reset the position of the file-pointer you're passing to it. For example:

```python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cbor2
>>> import io
>>> buf = io.BytesIO()
>>> buf.write(cbor2.dumps({"price":100,"Desc":"Hundred Dollars","level":"info","time":"2019-09-23T11:25:50-07:00"}))
73
>>> buf.write(cbor2.dumps({"price":1000,"Desc":"Thousand Dollars","level":"warn","time":"2019-09-23T11:25:50-07:00"}))
75
>>> buf.write(cbor2.dumps({"price":1000,"Desc":"Without TS","level":"warn"}))
37
>>> buf.seek(0)
0
```

So, at this point we've got a file-like object (buf) containing three log objects (dicts) simply written one after another. We've re-wound the file-pointer to the start, so let's try `load`:

```python3
>>> cbor2.load(buf)
{'Desc': 'Hundred Dollars', 'level': 'info', 'price': 100, 'time': '2019-09-23T11:25:50-07:00'}
>>> cbor2.load(buf)
{'Desc': 'Thousand Dollars', 'level': 'warn', 'price': 1000, 'time': '2019-09-23T11:25:50-07:00'}
>>> cbor2.load(buf)
{'Desc': 'Without TS', 'price': 1000, 'level': 'warn'}
>>> cbor2.load(buf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_cbor2.CBORDecodeError: premature end of stream (expected to read 1 bytes, got 0 instead)
```

As expected, we get back the items we wrote, in the order we wrote them. We get an error at the end because we've hit EOF and hence there's no leading byte to read. However, were more to be written to the stream, provided *our* file-pointer were left where it was (e.g. by duplication or rewinding) we can continue to read happily:

```python3
>>> buf.write(cbor2.dumps('foo'))
4
>>> buf.seek(-4, io.SEEK_CUR)
185
>>> cbor2.load(buf)
'foo'
```

On the other hand, if we use `loads`, I'd fully expect to receive only the first item back each time because we're asking the library to read from *the start of whatever string we pass*:

```python3
>>> cbor2.loads(buf.getvalue())
{'Desc': 'Hundred Dollars', 'level': 'info', 'price': 100, 'time': '2019-09-23T11:25:50-07:00'}
>>> cbor2.loads(buf.getvalue())
{'Desc': 'Hundred Dollars', 'level': 'info', 'price': 100, 'time': '2019-09-23T11:25:50-07:00'}
>>> cbor2.loads(buf.getvalue())
{'Desc': 'Hundred Dollars', 'level': 'info', 'price': 100, 'time': '2019-09-23T11:25:50-07:00'}
>>> cbor2.loads(buf.getvalue())
{'Desc': 'Hundred Dollars', 'level': 'info', 'price': 100, 'time': '2019-09-23T11:25:50-07:00'}
```

**Comment by toravir** [comment]
@waveform80 you are right - i was reading the entire file into a buffer and passing to load() and loads() when i attempted it. So for this sequence decoding to work - will pass the next offset and so on. When required to decode an entire string, will use StringIO or something like that to converted it into a stream and pass to load()..

Thanks. I will close this issue and will abandon the PR.
