### ISSUE TITLE
segfault of cbor2.load with python 3.8.2

### ISSUE THREAD

**Issue by gsalzer** [agronholm/cbor2#93]
```
$ pip install cbor2
Collecting cbor2
  Using cached cbor2-5.1.2.tar.gz (73 kB)
Building wheels for collected packages: cbor2
  Building wheel for cbor2 (setup.py) ... done
  Created wheel for cbor2: filename=cbor2-5.1.2-cp38-cp38-linux_x86_64.whl size=173916 sha256=a5197fd079744f4d0e09bebb936e7a3ee6b7a8d3ef62cdab1f05c5fbf1c9e089
  Stored in directory: /home/user/.cache/pip/wheels/ee/62/04/40cf369149e4f154952feb7c9a64f00ffa35b64cd2bfa5c3dd
Successfully built cbor2
Installing collected packages: cbor2
Successfully installed cbor2-5.1.2
$ python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
>>> import io,cbor2
>>> fp = io.BytesIO(b'\x9b78\x85\x19%\x1a\xe9\xca')
>>> cbor2.load(fp)
Segmentation fault (core dumped)
```

Expected behaviour: Exception

**Comment by Sekenre** [comment]
Thanks for finding this bug!

It's happening in both the Pure Python module(Memory Error) and the C Module(segfault) because we try to save some memory allocations by creating the array with the full length and then inserting each item.

Looks like that was a premature optimization! 😆 

I'll do some performance tests when I have time to see what the best fix is.

**Comment by Sekenre** [comment]
A similar problem occurs with bytestrings and string decoding, fortunately these raise MemoryError instead of segfault. I've got a fix ready anyway.

**Comment by gsalzer** [comment]
Thanks! I checked out the fix and it works.
