### ISSUE TITLE
Test failures on i386

### ISSUE THREAD

**Issue by bgermann** [agronholm/cbor2#99]
Running the test suite on i386 an error triggers: cannot fit 'int' into an index-sized integer
See https://salsa.debian.org/python-team/packages/cbor2/-/jobs/1064086

**Comment by lopsided98** [comment]
I'm seeing this on armv7l as well.

**Comment by Sekenre** [comment]
These particular tests are supposed to fail, but because it's a 32bit platform it's generating different exceptions. I will try to replicate this on my own hardware once I have time.

The main thing we want to avoid is the `_cbor2` module trying to pre-allocate all of the platform's RAM in the event of malformed data.

**Comment by lopsided98** [comment]
What I believe is happening is that the encoded length of the string doesn't fit in a 32-bit integer, so it fails with the overflow error before getting to the error the test is supposed to catch.
